article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard, name="dashboard"),
    path('addarticle/',views.addArticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment"),



]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('detail/<int:id>', views.detail, name="detail"),
    path('articles/', include("article.urls")),
    path('user/', include("user.urls"))     
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete=models.CASCADE, verbose_name= "Yazar")
    title = models.CharField(max_length=50, verbose_name="Başlık")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    article_image = models.FileField(blank = True, null = True, verbose_name="Makaleye Fotoğraf Ekleyin")

    def __str__(self):
        return self.title
    class Meta:
        ordering = ['-created_date']
class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE, verbose_name="Makale", related_name="comments")
    comment_author = models.CharField(max_length=50,verbose_name="İsim")
    comment_content = models.name = models.CharField(max_length=200,verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

article/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm
from .models import Article,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required

def articles(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    articles = Article.objects.all()    


    articles = Article.objects.all()

    return render(request,"articles.html",{"articles":articles})


# Create your views here.

def index(request):
    context = {
        "numbers":[1,2,3,4,5,6],
        
    }
    return render(request,"index.html",context)

def about(request):
    return render(request,"about.html")    

def detail(request,id):
    return HttpResponse("Detail:" + str(id))

@login_required(login_url = "user:login")
def dashboard(request):    
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles":articles
    }

    return render(request,"dashboard.html",context)

@login_required(login_url = "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()

        messages.success(request,"Makale Başarıyla Oluştu")
        return redirect("article:dashboard")

    return render(request,"addarticle.html",{"form":form})

def detail(request,id):
    #article = Article.objects.filter(id=id).first()
    article = get_object_or_404(Article,id = id)
    comments = article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})   

@login_required(login_url = "user:login")
def updateArticle(request,id):

    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance = article)

    if form.is_valid():        
        article = form.save(commit=False)
        article.author = request.user
        article.save()

        messages.success(request,"Makale Başarıyla Güncellendi")
        return redirect("article:dashboard")

    return render(request,"update.html",{"form":form})       
    
def deleteArticle(request,id):
    article = get_object_or_404(Article, id = id)

    article.delete()

    messages.success(request,"Makale Başarıyla silindi")

    return redirect("article:dashboard")

def addComment(request,id):
    article = get_object_or_404(Article,id=id)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author = comment_author, comment_content = comment_content)
        newComment.article = article
        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))     

templates/about.html
{% extends "layout.html" %} {% block body %}

<h3>Hakkında</h3>
<hr />
<p>
  Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium
  doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore
  veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim
  ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia
  consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque
  porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,
  adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et
  dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis
  nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex
  ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea
  voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem
  eum fugiat quo voluptas nulla pariatur?
</p>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Makale Oluştur</h3>
    <hr />
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %} {{form.media}} {{form|crispy}}
      <br />
      <button type="submit" class="btn btn-primary">Makale Oluştur</button>
    </form>
  </div>
</div>


{% endblock body %}

templates/articles.html
{% extends "layout.html" %} {% block body %}

  <div class="col-md-12 offset-md-2">
   <h3>Makaleler</h3>
    <hr />
    <div class="row">
      <form style="margin-bottom:20px;">
      {% csrf_token %}
        <input type="text" name="keyword" class="input-lg" />
        <button type="submit" class="btn btn-primary">Ara</button>
      </form>
    </div>    
  </div>
  {% if articles %} {% for article in articles %}
  <div class="col-md-12 offset-md-2">
    <div class="row">
      <div class="col-lg-8">
        <!-- Post content-->
        <article>
          <!-- Post header-->
          <header class="mb-4">
            <!-- Post title-->
            <a href={% url 'article:detail' article.id %}
              ><h2 class="mt-4">{{article.title}}</h2></a
            >
            <hr />
            <!-- Date/Time-->
            <p class="lead">{{article.created_date}}</p>
            <!-- Author-->
            <p>
              {{article.author.username}}<small> tarafından yayınlandı</small>
            </p>
          </header>
          <!-- Preview image figure-->
          {% if article.article_image %}
          <a href={% url 'article:detail' article.id %}>
            <img
              class="img-fluid rounded"
              src="{{article.article_image.url}}"
              alt="..."
          /></a>

          {% endif %}
          <!-- Post content-->
          <section class="mb-5">
            <p class="lead">{{article.content|safe|truncatewords:50}}</p>
            <a href="/articles/article/{{article.id}}" class="btn btn-primary"
              >Devamını Gör...</a
            >
            <hr />
          </section>
        </article>
      </div>
    </div>
  </div>

{% endfor %} {% else %}
<div class="alert alert-danger">Makale Bulunamadı..</div>
{% endif %} {% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<style>
p{
    font-family: arial;
}
</style>
<h1>Kontrol Paneli</h1>
<hr>
<p>
Hoşgeldiniz
<small>{{request.user.username}}</small>
</p>
<hr>
<a class="btn btn-danger" href="/articles/addarticle">Makale Ekle</a>
<br><br><br>
{% if articles %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Başlık</th>
      <th scope="col">Yazar</th>
      <th scope="col">Tarih</th>
      <th scope="col">Güncelle</th>
      <th scope="col">Sil</th>

    </tr>
  </thead>
  <tbody>
  {% for article in articles %}
   <tr>
      <th scope="row">{{article.id}}</th>
      <td><a href="/articles/article/{{article.id}}">{{article.title}}</a></td>
      <td>{{article.author.username}}</td>
      <td>{{article.created_date}}</td>
      <td><a href="/articles/update/{{article.id}}" class="btn btn-danger">Güncelle</a></td>
      <td><a href="/articles/delete/{{article.id}}" class="btn btn-danger">Sil</a></td>
    </tr>     
  {% endfor %}
   </table>
</tbody>
{% else %}
<div class ="alert alert-danger">
Henüz bir makaleniz bulunmuyor...
</div>

{% endif %}

{% endblock body %}

templates/detail.html
{% extends "layout.html" %} {% block body %}

<div class="row">
  <div class="col-lg-8">
    <!-- Post content-->
    <article>
      <!-- Post header-->
      <header class="mb-4">
        <!-- Post title-->
        <h2 class="mt-4">{{article.title}}</h2>
        <hr />
        <!-- Date/Time-Author -->
        <p>
          {{article.created_date}} <small>by</small> {{article.author.username}}
        </p>
        {% comment %}
        <!-- Post categories-->
        <a class="badge bg-secondary text-decoration-none link-light" href="#!"
          >Web Design</a
        >
        <a class="badge bg-secondary text-decoration-none link-light" href="#!"
          >Freebies</a
        >
        {% endcomment %}
      </header>
      <!-- Preview image figure-->
      {% if article.article_image %}
      <img
        class="img-fluid rounded"
        src="{{article.article_image.url}}"
        alt="..."
      />

      {% endif %}
      <!-- Post content-->
      <section class="mb-5">
        <p class="lead">{{article.content|safe}}</p>
      </section>
    </article>
    {% if comments %}
    {% for comment in comments %}
     <div class="d-flex">
        <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..."  /></div>
                <div class="ms-3">
                    <div class="fw-bold" style="margin-left:20px;margin-bottom:10px;"><h5>{{comment.comment_author}}</h5></div>
                    <div style="margin-left:40px;margin-bottom:-10px;">{{comment.comment_date}}</div> <br>
                    <div style="margin-left:40px;margin-bottom:20px;">{{comment.comment_content}}</div>
                    </div>
                        </div>
    
    {% endfor %}
    
    {% else %}
    <div class="alert alert-info">Henüz Yorum Yok..</div>
    {% endif %}
 
<section class="mb-5">
  <div class="card bg-light">
    <div class="card-body">
      <!-- Comment form-->
      <form method="post" class="mb-4" action ={% url "article:comment" article.id %}>
      {% csrf_token %}
      <div class="form-group">
    <label>İsminiz:</label>
    <input name="comment_author" class="form-control" placeholder="İsminiz..">
  </div>
      <label >Yorum:</label>
        <textarea
          class="form-control"
          rows="3"
          name="comment_content"
          placeholder="Yorumunuzu buraya yazın.."
        ></textarea>
        <button style="margin-top:10px;" type="submit" class="btn btn-primary">Yorum Yap</button>
      </form>
      <div class="d-flex mb-4">
        
    </div>
 </div>
</div>
    {% endblock body %}
  </div>
</section>

templates/index.html
{% extends "layout.html" %} {% block body %}

<div class="jumbotron text-center">
  <h3>Bloğuma Hoşgeldiniz</h3>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam hendrerit,
    justo nec feugiat auctor, nulla ante eleifend magna, id placerat libero
    dolor et ligula. Aliquam nulla urna, malesuada et ligula eget, ultricies
    cursus tellus. Duis sed ipsum quis dui faucibus efficitur. Pellentesque
    finibus venenatis tellus sit amet sodales. Suspendisse maximus semper
    turpis, non suscipit arcu aliquam vitae. Praesent metus leo, gravida nec
    tincidunt ut, malesuada ultricies elit. Donec vitae leo sit amet felis
    cursus bibendum. Fusce nisi sem, aliquam id ligula non, faucibus luctus
    felis. Praesent pulvinar ipsum vitae tincidunt blandit. Mauris eu ex
    molestie, convallis massa ut, ornare risus.
  </p>
</div>
<p>
  {% if request.user.is_authenticated %}
  {% else %}
  {% endif %}
</p>
{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    {% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> {% endcomment %}
    <title>MG Blog</title>
</head>
<body>    
    {% include "includes/navbar.html" %}
    <div style="margin-top:100px; margin-botton:100px;" class = "container">

    

    {% if messages %}
        
        {% for message in messages %}
        {% if message.tags == "info" %}
            <div{% if message.tags %} class="alert alert-danger"{% endif %}>{{message}}</div> 
        {% else %}
            <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{message}}</div> 
        {% endif %}
                      
        {% endfor %}   
               
    {% endif %}

    {% block body %}
    
    {% endblock body %}




<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery-3.6.1.js' %}"></script>
    
{% comment %} <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> {% endcomment %}
</body>
</html>

templates/login.html
{% extends "layout.html" %} 
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Giriş yap</h3>
    <hr />
    <form method="post">
      {% csrf_token %} {{form|crispy}}
      <br />
      <button type="submit" class="btn btn-primary">Giriş Yap</button>
    </form>
  </div>
</div>
{% endblock body %}

templates/register.html
{% extends "layout.html" %} 
,{% block body %}
{% load crispy_forms_tags %}
<h3>Kayıt ol</h3>
<hr />

<form method="post">
  {% csrf_token %} {{form|crispy}}
  <br />
  <button type="submit" class="btn btn-primary">Kayıt Ol</button>
  <form>{% endblock body %}</form>
</form>

templates/update.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Makale Güncelle</h3>
    <hr />
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %} {{form.media}} {{form|crispy}}
      <br />
      <button type="submit" class="btn btn-primary">Makale güncelle</button>
    </form>
  </div>
</div>


{% endblock body %}